// <auto-generated />
namespace FEL_JAMIRA_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add));
        
        string IMigrationMetadata.Id
        {
            get { return "201910081833497_add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
