// <auto-generated />
namespace FEL_JAMIRA_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _18 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_18));
        
        string IMigrationMetadata.Id
        {
            get { return "201908041850445_1.8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
